export enum EventType {
  WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED",
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_USER_ADDED = "PROJECT_USER_ADDED",
  PROJECT_USER_REMOVED = "PROJECT_USER_REMOVED",
  PROJECT_USER_PERMISSION_GRANTED = "PROJECT_USER_PERMISSION_GRANTED",
  PROJECT_USER_PERMISSION_REVOKED = "PROJECT_USER_PERMISSION_REVOKED",
}
