export enum ProjectPermission {
  PROJECT_MANAGE_USERS = "PROJECT_MANAGE_USERS",
  PROJECT_READ_USERS = "PROJECT_READ_USERS",
  PROJECT_READ_EVENTS = "PROJECT_READ_EVENTS",
  PROJECT_READ_API_KEY = "PROJECT_READ_API_KEY",
}